import type { CapabilityVersionPreset } from "./capabilityManifestShared";

// This file is auto-generated by scripts/generate-capability-manifest-presets.ts.
// Do not edit it manually.
export const capabilityVersionPresets = [
  {
    "version": "nnrp-1-preview2",
    "title": {
      "zh": "NNRP/1 Preview2",
      "en": "NNRP/1 Preview2"
    },
    "note": {
      "zh": "覆盖 Preview2 的线缆向量、控制面、数据面与传输 smoke 能力。",
      "en": "Covers the preview2 wire vectors, control plane, data plane, and transport smoke capabilities."
    },
    "recommendedPath": "conformance/nnrp-1-preview2.capabilities.json",
    "capabilities": [
      {
        "token": "control.client_hello",
        "layers": "L0",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "CLIENT_HELLO 固定元数据块。",
          "en": "CLIENT_HELLO fixed metadata block."
        }
      },
      {
        "token": "control.session_patch_ack",
        "layers": "L0",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "SESSION_PATCH_ACK 固定元数据块。",
          "en": "SESSION_PATCH_ACK fixed metadata block."
        }
      },
      {
        "token": "flow_update",
        "layers": "L0 / L1",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "FLOW_UPDATE 的线缆与语义双层约束。",
          "en": "FLOW_UPDATE at both wire and semantic layers."
        }
      },
      {
        "token": "result_hint",
        "layers": "L0 / L1",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "RESULT_HINT 的固定包体与语义验证。",
          "en": "RESULT_HINT wire shape and metadata semantics."
        }
      },
      {
        "token": "frame_submit.mixed",
        "layers": "L0 / L1",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "混合提交模式的 FRAME_SUBMIT 主路径。",
          "en": "The mixed-submit FRAME_SUBMIT hot path."
        },
        "combination": {
          "zh": "需同时声明 payload.tensor。",
          "en": "Must also claim payload.tensor."
        }
      },
      {
        "token": "payload.tensor",
        "layers": "L0 / L1",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "Tensor profile 主路径依赖能力。",
          "en": "Dependency capability for the tensor-profile main path."
        },
        "combination": {
          "zh": "常与 frame_submit.mixed、result_push.partial、result_push.stale_reuse 组合。",
          "en": "Usually paired with frame_submit.mixed, result_push.partial, and result_push.stale_reuse."
        }
      },
      {
        "token": "result_push.partial",
        "layers": "L0 / L1",
        "categories": [
          "mandatory",
          "optional"
        ],
        "description": {
          "zh": "部分交付结果路径。",
          "en": "Partial-delivery results."
        },
        "combination": {
          "zh": "mandatory 主结果路径还需 result_push.stale_reuse 与 payload.tensor。",
          "en": "The mandatory result path also needs result_push.stale_reuse and payload.tensor."
        }
      },
      {
        "token": "result_push.stale_reuse",
        "layers": "L0 / L1",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "旧帧复用语义。",
          "en": "Stale-frame reuse semantics."
        },
        "combination": {
          "zh": "需同时声明 result_push.partial 与 payload.tensor。",
          "en": "Must also claim result_push.partial and payload.tensor."
        }
      },
      {
        "token": "body_region.prelude",
        "layers": "L0",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "固定 body-region prelude 的编码布局。",
          "en": "Stable encoding layout for the body-region prelude."
        }
      },
      {
        "token": "object_reference.cache",
        "layers": "L0 / L1",
        "categories": [
          "mandatory",
          "optional"
        ],
        "description": {
          "zh": "缓存对象引用块，以及结果体中的引用解析。",
          "en": "Cache object-reference blocks and result-body reference resolution."
        },
        "combination": {
          "zh": "L1 可选检查还会与 result_push.partial 组合。",
          "en": "The L1 optional check also combines with result_push.partial."
        }
      },
      {
        "token": "payload.typed",
        "layers": "L0 / L1",
        "categories": [
          "mandatory",
          "optional"
        ],
        "description": {
          "zh": "非 tensor typed payload 的 descriptor 与 region 打包。",
          "en": "Non-tensor typed payload descriptors and region packing."
        }
      },
      {
        "token": "cache.lifecycle",
        "layers": "L1",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "缓存对象的分配、确认、失效与命名空间管理。",
          "en": "Cache-object allocation, acknowledgement, invalidation, and namespace handling."
        }
      },
      {
        "token": "transport.probe",
        "layers": "L1 / L3",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "探测元数据与传输选择逻辑。",
          "en": "Probe metadata and transport-selection logic."
        }
      },
      {
        "token": "result_push.degraded",
        "layers": "L1",
        "categories": [
          "experimental"
        ],
        "description": {
          "zh": "degraded/fallback 结果路径，目前仅信息性跟踪。",
          "en": "Degraded / fallback result path, currently informational only."
        }
      },
      {
        "token": "transport.tcp",
        "layers": "L3",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "TCP smoke 互通能力。",
          "en": "TCP smoke interoperability."
        }
      },
      {
        "token": "transport.quic",
        "layers": "L3",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "QUIC smoke 互通能力。",
          "en": "QUIC smoke interoperability."
        }
      }
    ]
  },
  {
    "version": "nnrp-1-preview3",
    "title": {
      "zh": "NNRP/1 Preview3",
      "en": "NNRP/1 Preview3"
    },
    "note": {
      "zh": "覆盖 Preview3 当前 mandatory core，以及正在演进的 optional / experimental 能力。",
      "en": "Covers the current Preview3 mandatory core plus the evolving optional and experimental capabilities."
    },
    "recommendedPath": "conformance/nnrp-1-preview3.capabilities.json",
    "capabilities": [
      {
        "token": "handshake.basic",
        "layers": "L1",
        "categories": [
          "mandatory"
        ],
        "description": {
          "zh": "最小握手与能力协商流程。",
          "en": "Minimum handshake and capability negotiation flow."
        }
      },
      {
        "token": "session.open_close",
        "layers": "L0 / L1",
        "categories": [
          "mandatory",
          "optional"
        ],
        "description": {
          "zh": "会话打开、维持与关闭状态机。",
          "en": "Session open, maintain, and close state machine."
        },
        "combination": {
          "zh": "Appears in multiple combined selections: session.resume; session.multi_session.",
          "en": "Appears in multiple combined selections: session.resume; session.multi_session."
        }
      },
      {
        "token": "frame_submit.tensor.inline",
        "layers": "L1 / L2",
        "categories": [
          "mandatory",
          "optional"
        ],
        "description": {
          "zh": "最小 inline tensor 提交路径。",
          "en": "Minimum inline tensor submit path."
        },
        "combination": {
          "zh": "需同时声明 result_push.basic。",
          "en": "Must also claim result_push.basic."
        }
      },
      {
        "token": "result_push.basic",
        "layers": "L1 / L2",
        "categories": [
          "mandatory",
          "optional"
        ],
        "description": {
          "zh": "与最小提交路径兼容的结果返回。",
          "en": "Result return compatible with the minimum submit path."
        },
        "combination": {
          "zh": "需同时声明 frame_submit.tensor.inline。",
          "en": "Must also claim frame_submit.tensor.inline."
        }
      },
      {
        "token": "transport.quic",
        "layers": "L3",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Preview3 QUIC 最小互通传输。",
          "en": "Preview3 minimum QUIC interoperability transport."
        }
      },
      {
        "token": "transport.tcp",
        "layers": "L3",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Preview3 TCP 最小互通传输。",
          "en": "Preview3 minimum TCP interoperability transport."
        }
      },
      {
        "token": "flow_update",
        "layers": "L0 / L1",
        "categories": [
          "experimental"
        ],
        "description": {
          "zh": "尚未冻结进 mandatory core 的 flow-control 语义。",
          "en": "Flow-control semantics not yet frozen into the mandatory core."
        }
      },
      {
        "token": "session.resume",
        "layers": "L0 / L1",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Derived from 5 cases. Round-trip the canonical Preview3 SESSION_OPEN resume-request metadata vector, including resume token length and resumed-session defaults. Round-trip the canonical Preview3 SESSION_OPEN_ACK resumed metadata vector and preserve the resumed session_status semantics. Round-trip the canonical Preview3 SESSION_OPEN_ACK resume-rejected metadata vector and preserve the stable resume_rejected error code. Validate Preview3 resume_from_operation_id semantics, including resumed SESSION_OPEN_ACK status and the requirement that session recovery resumes from an operation waterline rather than from frame-level objects. Validate Preview3 resume rejection behavior: invalid, expired, unauthorized, or incompatible resume_token requests must return session_error_code=resume_rejected without inventing a frame-level recovery path.",
          "en": "Derived from 5 cases. Round-trip the canonical Preview3 SESSION_OPEN resume-request metadata vector, including resume token length and resumed-session defaults. Round-trip the canonical Preview3 SESSION_OPEN_ACK resumed metadata vector and preserve the resumed session_status semantics. Round-trip the canonical Preview3 SESSION_OPEN_ACK resume-rejected metadata vector and preserve the stable resume_rejected error code. Validate Preview3 resume_from_operation_id semantics, including resumed SESSION_OPEN_ACK status and the requirement that session recovery resumes from an operation waterline rather than from frame-level objects. Validate Preview3 resume rejection behavior: invalid, expired, unauthorized, or incompatible resume_token requests must return session_error_code=resume_rejected without inventing a frame-level recovery path."
        },
        "combination": {
          "zh": "Also selected with session.open_close.",
          "en": "Also selected with session.open_close."
        }
      },
      {
        "token": "schema.registry",
        "layers": "L0 / L1 / L2",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Derived from 9 cases. Round-trip the canonical Preview3 32-byte schema descriptor header vector, including schema_flags and default stream semantics. Round-trip the canonical Preview3 schema_error_code raw wire values and preserve the frozen schema_unknown, schema_version_unknown, schema_hash_conflict, schema_incompatible, schema_dependency_missing, and schema_update_rejected assignments. Validate the Preview3 32-byte schema descriptor header layout, including stable field offsets for schema_id, schema_version, profile binding, and applicability scope. Validate Preview3 schema_flags bit assignments, including cacheable, critical, and default-bindable semantics without allowing private bindings to redefine the public bit vocabulary. Validate Preview3 default stream semantics in schema descriptors, including append-style token streams versus single-shot payload bindings. Validate Preview3 schema install and update flows, including stable schema_error_code reporting for schema_unknown, schema_version_unknown, and schema_hash_conflict outcomes. Validate Preview3 schema invalidate and conflict flows, including schema_incompatible, schema_dependency_missing, and schema_update_rejected handling. Validate Preview3 schema-registry error mapping at the SDK boundary: when a critical schema, version, or dependency is unknown, the binding must surface stable public schema_error_code outcomes such as schema_unknown, schema_version_unknown, or schema_dependency_missing instead of silently skipping the descriptor or rewriting the failure as a generic transport error. Validate Preview3 schema conflict reporting remains protocol-shaped after crossing a driver or FFI layer: schema_hash_conflict and schema_update_rejected must stay distinct public outcomes rather than being merged into one host-specific installation failure.",
          "en": "Derived from 9 cases. Round-trip the canonical Preview3 32-byte schema descriptor header vector, including schema_flags and default stream semantics. Round-trip the canonical Preview3 schema_error_code raw wire values and preserve the frozen schema_unknown, schema_version_unknown, schema_hash_conflict, schema_incompatible, schema_dependency_missing, and schema_update_rejected assignments. Validate the Preview3 32-byte schema descriptor header layout, including stable field offsets for schema_id, schema_version, profile binding, and applicability scope. Validate Preview3 schema_flags bit assignments, including cacheable, critical, and default-bindable semantics without allowing private bindings to redefine the public bit vocabulary. Validate Preview3 default stream semantics in schema descriptors, including append-style token streams versus single-shot payload bindings. Validate Preview3 schema install and update flows, including stable schema_error_code reporting for schema_unknown, schema_version_unknown, and schema_hash_conflict outcomes. Validate Preview3 schema invalidate and conflict flows, including schema_incompatible, schema_dependency_missing, and schema_update_rejected handling. Validate Preview3 schema-registry error mapping at the SDK boundary: when a critical schema, version, or dependency is unknown, the binding must surface stable public schema_error_code outcomes such as schema_unknown, schema_version_unknown, or schema_dependency_missing instead of silently skipping the descriptor or rewriting the failure as a generic transport error. Validate Preview3 schema conflict reporting remains protocol-shaped after crossing a driver or FFI layer: schema_hash_conflict and schema_update_rejected must stay distinct public outcomes rather than being merged into one host-specific installation failure."
        }
      },
      {
        "token": "cache.lifecycle",
        "layers": "L0 / L1",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Derived from 9 cases. Round-trip the canonical Preview3 cache_error_code raw wire values and preserve the frozen cache_miss, lease_expired, version_mismatch, dependency_invalid, and schema_mismatch family assignments. Validate Preview3 cache lease_owner_scope semantics, including the requirement that lease ownership remains a public interoperability contract rather than a runtime-private policy hint. Validate Preview3 object_version monotonicity, including rejection of stale writes and the requirement that version comparison is performed on the public cache object rather than on runtime-private internals. Validate Preview3 dependency_invalid behavior when a cache object depends on schema or cache entries that are expired, revoked, or replaced underneath it. Validate Preview3 cache_error_code=cache_miss is reported for missing public cache objects rather than collapsing the outcome into a generic transport or validation failure. Validate Preview3 cache_error_code=lease_expired when a lease-backed cache object is accessed after its public lease window closes. Validate Preview3 cache_error_code=version_mismatch when callers target the wrong object_version instead of silently rebinding to a newer cache object version. Validate Preview3 cache_error_code=dependency_invalid when dependency chains become unusable even though the directly addressed object still exists. Validate Preview3 cache_error_code=schema_mismatch when a cached object is addressed through an incompatible public schema binding.",
          "en": "Derived from 9 cases. Round-trip the canonical Preview3 cache_error_code raw wire values and preserve the frozen cache_miss, lease_expired, version_mismatch, dependency_invalid, and schema_mismatch family assignments. Validate Preview3 cache lease_owner_scope semantics, including the requirement that lease ownership remains a public interoperability contract rather than a runtime-private policy hint. Validate Preview3 object_version monotonicity, including rejection of stale writes and the requirement that version comparison is performed on the public cache object rather than on runtime-private internals. Validate Preview3 dependency_invalid behavior when a cache object depends on schema or cache entries that are expired, revoked, or replaced underneath it. Validate Preview3 cache_error_code=cache_miss is reported for missing public cache objects rather than collapsing the outcome into a generic transport or validation failure. Validate Preview3 cache_error_code=lease_expired when a lease-backed cache object is accessed after its public lease window closes. Validate Preview3 cache_error_code=version_mismatch when callers target the wrong object_version instead of silently rebinding to a newer cache object version. Validate Preview3 cache_error_code=dependency_invalid when dependency chains become unusable even though the directly addressed object still exists. Validate Preview3 cache_error_code=schema_mismatch when a cached object is addressed through an incompatible public schema binding."
        }
      },
      {
        "token": "payload.typed",
        "layers": "L0 / L1 / L2",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Derived from 6 cases. Round-trip the canonical Preview3 24-byte typed payload descriptor vector, including partial semantics and schema binding fields. Validate the Preview3 24-byte typed payload descriptor layout, descriptor flag semantics, and offset/length interpretation rules. Validate Preview3 token-profile partial semantics, including consumable chunks, stop-reason boundaries, and non-tensor sequence interpretation. Validate Preview3 typed-payload buffer ownership at the SDK or FFI boundary: callback, polling, or borrowed-buffer adapters must preserve offset and length semantics relative to the typed payload frame region instead of rebasing slices against a whole-packet body or a runtime-private subregion. Validate Preview3 typed-payload descriptor exposure stays consistent across callback and polling drive modes: the same public descriptor fields, flags, and stream semantics must be observable without a binding rewriting them into transport-local or runtime-private metadata. Validate Preview3 token-profile partial delivery stays consumable and non-terminal across callback and polling adapters: the binding must preserve chunk ordering, partial versus terminal meaning, and stop-reason visibility instead of collapsing them into one generic text-stream callback.",
          "en": "Derived from 6 cases. Round-trip the canonical Preview3 24-byte typed payload descriptor vector, including partial semantics and schema binding fields. Validate the Preview3 24-byte typed payload descriptor layout, descriptor flag semantics, and offset/length interpretation rules. Validate Preview3 token-profile partial semantics, including consumable chunks, stop-reason boundaries, and non-tensor sequence interpretation. Validate Preview3 typed-payload buffer ownership at the SDK or FFI boundary: callback, polling, or borrowed-buffer adapters must preserve offset and length semantics relative to the typed payload frame region instead of rebasing slices against a whole-packet body or a runtime-private subregion. Validate Preview3 typed-payload descriptor exposure stays consistent across callback and polling drive modes: the same public descriptor fields, flags, and stream semantics must be observable without a binding rewriting them into transport-local or runtime-private metadata. Validate Preview3 token-profile partial delivery stays consumable and non-terminal across callback and polling adapters: the binding must preserve chunk ordering, partial versus terminal meaning, and stop-reason visibility instead of collapsing them into one generic text-stream callback."
        },
        "combination": {
          "zh": "Also selected with profile.token.",
          "en": "Also selected with profile.token."
        }
      },
      {
        "token": "session.multi_session",
        "layers": "L1",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Derived from 3 cases. Validate Preview3 treats a connection as a multi-session container by allowing multiple live session_ids without cross-session state or credit leakage. Validate closing one Preview3 session does not implicitly close the transport or invalidate sibling sessions that remain active on the same connection. Validate connection-level CLOSE tears down remaining Preview3 sessions as a container shutdown, rather than reusing per-session close semantics or permitting further session traffic.",
          "en": "Derived from 3 cases. Validate Preview3 treats a connection as a multi-session container by allowing multiple live session_ids without cross-session state or credit leakage. Validate closing one Preview3 session does not implicitly close the transport or invalidate sibling sessions that remain active on the same connection. Validate connection-level CLOSE tears down remaining Preview3 sessions as a container shutdown, rather than reusing per-session close semantics or permitting further session traffic."
        },
        "combination": {
          "zh": "Also selected with session.open_close.",
          "en": "Also selected with session.open_close."
        }
      },
      {
        "token": "operation.lifecycle",
        "layers": "L1",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Derived from 3 cases. Validate Preview3 lifecycle progression for accepted, running, partial, and completed states without collapsing partial delivery into terminal completion. Validate Preview3 waiting_tool as a public lifecycle state while keeping tool arguments, tool results, and rich event payloads inside schema/profile payloads rather than fixed public metadata. Validate Preview3 terminal lifecycle resolution keeps cancelled, failed, superseded, and completed distinct, rather than collapsing all terminal outcomes into one generic final state.",
          "en": "Derived from 3 cases. Validate Preview3 lifecycle progression for accepted, running, partial, and completed states without collapsing partial delivery into terminal completion. Validate Preview3 waiting_tool as a public lifecycle state while keeping tool arguments, tool results, and rich event payloads inside schema/profile payloads rather than fixed public metadata. Validate Preview3 terminal lifecycle resolution keeps cancelled, failed, superseded, and completed distinct, rather than collapsing all terminal outcomes into one generic final state."
        }
      },
      {
        "token": "operation.cancel_scope",
        "layers": "L1",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Validate Preview3 cancel_scope semantics across single-operation, subtree, operation_group, and whole-session cancellation boundaries.",
          "en": "Validate Preview3 cancel_scope semantics across single-operation, subtree, operation_group, and whole-session cancellation boundaries."
        }
      },
      {
        "token": "profile.token",
        "layers": "L1 / L2",
        "categories": [
          "optional"
        ],
        "description": {
          "zh": "Derived from 2 cases. Validate Preview3 token-profile partial semantics, including consumable chunks, stop-reason boundaries, and non-tensor sequence interpretation. Validate Preview3 token-profile partial delivery stays consumable and non-terminal across callback and polling adapters: the binding must preserve chunk ordering, partial versus terminal meaning, and stop-reason visibility instead of collapsing them into one generic text-stream callback.",
          "en": "Derived from 2 cases. Validate Preview3 token-profile partial semantics, including consumable chunks, stop-reason boundaries, and non-tensor sequence interpretation. Validate Preview3 token-profile partial delivery stays consumable and non-terminal across callback and polling adapters: the binding must preserve chunk ordering, partial versus terminal meaning, and stop-reason visibility instead of collapsing them into one generic text-stream callback."
        },
        "combination": {
          "zh": "Also selected with payload.typed.",
          "en": "Also selected with payload.typed."
        }
      }
    ]
  }
] satisfies CapabilityVersionPreset[];
